---
  - name: restart node exporter
    service:
      name: node_exporter
      state: restarted
    become: true

  - name: reload systemctl daemon
    systemd:
      daemon_reload: yes
    become: true
